{% set version = "0.12.1" %}

package:
  name: tensorflow-addons
  version: {{ version }}

source:
  git_url: https://github.com/tensorflow/addons.git
  git_rev: v{{ version }}
  patches:
    - 0001-Fix-build-on-ppc.patch  #[ppc64le] 

build:
  number: 1
  string: py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}
  
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel {{ bazel }}
    - git >={{ git }}
  host:
    - python  {{ python }}
    - tensorflow-base {{ tensorflow }}
  run:
    - python  {{ python }}
    - tensorflow-base {{ tensorflow }}

about:
  home: https://www.tensorflow.org/addons/
  license: Apache-2.0
  license_family: Apache
  license_file: {{ SRC_DIR }}/LICENSE
  summary: "A library that implements new functionality not available in core TensorFlow."
  description: |
     TensorFlow Addons is a repository of contributions that conform to well-established API patterns,
     but implements new functionality not available in core.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
