{% set version = "0.12.1" %}
{% set build_ext_version = version %}
{% set build_ext = "cuda" if build_type == 'cuda' else "cpu" %}
{% set proc_build_number = "1" %}

package:
  name: tensorflow-addons-ext
  version: {{ version }}

source:
  git_url: https://github.com/tensorflow/addons.git
  git_rev: v{{ version }}
  patches:
    - 0001-Fix-build-on-ppc.patch  #[ppc64le] 

build:
  number: 2
  run_exports:
    - {{ pin_subpackage("tensorflow-addons", max_pin="x.x.x") }}

outputs:
  - name: tensorflow-addons-proc
    version: {{ build_ext_version }}
    build:
      number: {{ proc_build_number }}
      string: {{ build_ext }}
    test:
      commands:
        - exit 0
    about:
      home: https://www.tensorflow.org/addons/
      license: Apache-2.0
      license_family: Apache
      license_file: {{ SRC_DIR }}/LICENSE
      summary: "A meta-package to select TensorFlow addons build variant"

  - name: tensorflow-addons
    script: build-addons.sh
    version: {{ version }}
    build:
      string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ build_ext }}{{ cudatoolkit | replace(".*", "") }} #[build_type == 'cuda']
      string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ build_ext }}  #[build_type == 'cpu']
{% if build_type == 'cuda' %}
      script_env:
        - CUDA_HOME
{% endif %}
      run_exports:
        - {{ pin_subpackage("tensorflow-addons", max_pin="x.x.x") }}
      track_features:
        {{ "- tensorflow-addons-cuda" if build_type == 'cuda' else "" }} 
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - bazel {{ bazel }}
        - git >={{ git }}
      host:
        - python  {{ python }}
{% if build_type == 'cuda' %}
        - cudatoolkit {{ cudatoolkit }}
        - cudnn {{ cudnn }}
        - nccl {{ nccl }}
{% endif %}
        - tensorflow-base {{ tensorflow }}
      run:
        - python  {{ python }}
{% if build_type == 'cuda' %}
        - cudatoolkit {{ cudatoolkit }}
        - cudnn {{ cudnn }}
        - nccl {{ nccl }}
{% endif %}
        - tensorflow-base {{ tensorflow }}
      run_constrained:
        - tensorflow-addons-proc * {{ build_ext }}


    about:
      home: https://www.tensorflow.org/addons/
      license: Apache-2.0
      license_family: Apache
      license_file: {{ SRC_DIR }}/LICENSE
      summary: "A library that implements new functionality not available in core TensorFlow."
      description: |
         TensorFlow Addons is a repository of contributions that conform to well-established API patterns,
         but implements new functionality not available in core.

#    test:
#      imports:
        #- tensorflow-addons

about:
  home: https://www.tensorflow.org/addons/
  license: Apache-2.0
  license_family: Apache
  license_file: {{ SRC_DIR }}/LICENSE
  summary: "A library that implements new functionality not available in core TensorFlow."
  description: |
     TensorFlow Addons is a repository of contributions that conform to well-established API patterns,
     but implements new functionality not available in core.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
